"""initial schema from models

Revision ID: 8b0199d7017b
Revises: 
Create Date: 2026-04-12 10:03:08.757961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0199d7017b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.add_column('estimates', sa.Column('review_status', sa.String(length=30), nullable=True))
    op.add_column('estimates', sa.Column('review_reason', sa.Text(), nullable=True))
    op.add_column('estimates', sa.Column('adjustments_json', sa.Text(), nullable=True))
    op.alter_column('estimates', 'estimate_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'customer_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'customer_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'customer_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'actual_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'actual_cy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'actual_truck_fraction',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'correction_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'preferred_contact',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'phone'"))
    op.alter_column('estimates', 'model_used',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'capture_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'remote'"))
    op.alter_column('estimates', 'confidence_bucket',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'scene_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'occupancy_class',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'appointment_contact_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'appointment_preferred_day',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'appointment_preferred_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'appointment_requested_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.create_index(op.f('ix_estimates_created_at'), 'estimates', ['created_at'], unique=False)
    op.create_index(op.f('ix_estimates_team_member_id'), 'estimates', ['team_member_id'], unique=False)
    op.create_index(op.f('ix_estimates_user_id'), 'estimates', ['user_id'], unique=False)
    op.alter_column('item_reference_library', 'cubic_yards',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('plan_configs', 'tier_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('plan_configs', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'company_slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'company_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'company_logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'price_per_cy_standard',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'price_per_cy_heavy',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'America/Chicago'"))
    op.alter_column('users', 'billing_cycle_start',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'overage_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'warn_and_charge'"))
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'owner'"))
    op.alter_column('users', 'industry',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'junk_removal'"))
    op.alter_column('users', 'free_trial_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'google_tag_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'fb_pixel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_index(op.f('ix_users_company_slug'), 'users', ['company_slug'], unique=False)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_company_slug'), table_name='users')
    op.alter_column('users', 'fb_pixel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'google_tag_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'free_trial_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'industry',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'junk_removal'"))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'owner'"))
    op.alter_column('users', 'overage_mode',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'warn_and_charge'"))
    op.alter_column('users', 'billing_cycle_start',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'timezone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'America/Chicago'"))
    op.alter_column('users', 'price_per_cy_heavy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'price_per_cy_standard',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('users', 'company_logo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'company_phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'company_slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('plan_configs', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plan_configs', 'tier_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item_reference_library', 'cubic_yards',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_index(op.f('ix_estimates_user_id'), table_name='estimates')
    op.drop_index(op.f('ix_estimates_team_member_id'), table_name='estimates')
    op.drop_index(op.f('ix_estimates_created_at'), table_name='estimates')
    op.alter_column('estimates', 'appointment_requested_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'appointment_preferred_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'appointment_preferred_day',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'appointment_contact_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'occupancy_class',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'scene_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'confidence_bucket',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'capture_mode',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'remote'"))
    op.alter_column('estimates', 'model_used',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'preferred_contact',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'phone'"))
    op.alter_column('estimates', 'correction_reason',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'actual_truck_fraction',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'actual_cy',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'actual_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('estimates', 'customer_phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'customer_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'customer_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('estimates', 'estimate_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
    op.drop_column('estimates', 'adjustments_json')
    op.drop_column('estimates', 'review_reason')
    op.drop_column('estimates', 'review_status')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
